name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  rust-checks:
    name: Rust checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: rustup toolchain install stable --profile minimal
      - uses: Swatinem/rust-cache@v2.7.3
        with:
          save-if: ${{ github.ref == 'refs/heads/master' }}
      - name: Check
        run: cargo check --verbose

  ui-checks:
    name: UI checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: web-ui/package-lock.json
      - name: Install dependencies
        run: npm ci
        working-directory: web-ui
      - name: Lint
        run: npm run lint
        working-directory: web-ui
      - name: Type check
        run: npm run typecheck
        working-directory: web-ui
      - name: Build
        run: npm run build
        working-directory: web-ui
